"""empty message

Revision ID: dcb2edef0d3f
Revises: e3d18f4e36f7
Create Date: 2025-06-24 04:01:01.399630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb2edef0d3f'
down_revision = 'e3d18f4e36f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_characters_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_characters_character_id_fkey', 'characters', ['character_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
